accounts/urls.py
from django.contrib import admin
from django.urls import path

from lms import settings
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('', index, name='index'),
    path('login/',Login.as_view(),name='login'),
    path('registration/',Registration.as_view(),name='registration'),
    path('logout/',Logout,name='logout'),
    path('profile/<int:pk>/',ProfileView.as_view(),name="profile"),
    path('profile/update/<int:pk>/',ProfileUpdate.as_view(),name="update-profile"),
]

book/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [

    url(r'ajax_calls/search/$', views.autocompleteModel),
    path('',views.BookSearch.as_view(),name='booksearch'),
    path('issued/',views.MyIssuedBook.as_view(),name='myissuedbook'),
    path('issued/approval/',views.ApproveReq.as_view(),name='approval'),
    path('issued/return/',views.ReturnBook.as_view(),name='bookreturn'),
    path('issued/delete/',views.DeleteRequest.as_view(),name='delreq'),
    path('list/',views.AllBookList.as_view(),name='booklist'),
    path('list/request/',views.MyRequestList.as_view(),name='reqlist'),
    path('issued/delreq/',views.DeleteRequestUser.as_view(),name='delrequser'),
    path('issued/list/',views.IssuedBooklist.as_view(),name='issuedlist'),
    path('registration/',views.BookCreate.as_view(),name='bookadd'),
    path('update/<int:pk>/',views.BookUpdate.as_view(),name='bookupdate'),
    path('delete/<int:pk>/',views.BookDelete.as_view(),name='bookdelete'),
    path('delete/waitingreq/',views.WaitingReqDelete.as_view(),name='waitingreqdelete'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('book/',include('book.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

GENDER = (('M', 'Male'),
          ('F', 'Female'))


class User(AbstractUser):
    name = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    gender = models.CharField(max_length=1, choices=GENDER)
    contact = models.PositiveIntegerField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('accounts:profile',kwargs={'pk':self.pk})

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User

# GENDER_CHOICE=(('M','Male'),
#                ('F','Female'))


class RegistrationForm(UserCreationForm):
    # gender = forms.CharField(widget=forms.Select(choices=GENDER_CHOICE))

    class Meta:
        model = User
        fields = ('name','username','email','gender','contact', 'password1', 'password2')


class LoginForm(forms.Form):
    email = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())


class BookSearch(forms.Form):
    bookinput= forms.CharField()

accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect

from book.models import IssuedBook
from lms import settings
from .forms import *
from django.views import View, generic
from django.contrib.messages.views import messages


def index(request):
    return render(request, 'accounts/index.html')


class Login(View):
    def get(self, request):
        form = LoginForm()
        messages.warning(request, 'Please Login in order to continue!')
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)
            if user is not None:
                if user.is_staff:
                    login(request, user)
                    return redirect('book:approval')
                login(request, user)
                return redirect('book:booksearch')
            else:
                messages.error(request, 'User Not Found please Enter Valid data' + str(form.errors))
        return render(request, 'accounts/login.html', {'form': form})


def Logout(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


class Registration(View):

    def get(self, request):
        form = RegistrationForm()
        return render(request, 'accounts/registrations.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            messages.error(request, 'Registration fail..')
            return render(request, 'accounts/registrations.html', {'form': form})
        messages.info(request, 'Registration successfully..')
        return redirect('accounts:login')


class ProfileView(generic.DetailView):
    model = User
    template_name = 'accounts/profile.html'
    extra_context = {'form': RegistrationForm()}

class ProfileUpdate(generic.UpdateView):
    model = User
    fields = ['name', 'username', 'gender', 'contact']

accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<!--    <script src="{% static 'js/bootstrap_min_css.js' %}"></script>-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	  <script src="{% static 'js/autocomplete.js' %}"></script>

</head>
<body class="bg-img">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
            <a class="navbar-brand" href="{% url 'accounts:index' %}">Library</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li class="{% if request.resolver_match.url_name == 'booksearch' %}active{%endif%}">
                    <a href="{% url 'book:booksearch' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Issue Book
                    </a>
                    </li>

                <li class="{% if request.resolver_match.url_name == 'reqlist' %}active{%endif%}">
                    <a href="{% url 'book:reqlist' %}">
                        <span class="glyphicon glyphicon-export" aria-hidden="true"></span>&nbsp;My Requests
                    </a>
                    </li>

                <li class="{% if request.resolver_match.url_name == 'booklist' %}active{%endif%}">
                    <a href="{% url 'book:booklist' %}">
                        <span class="bi bi-book" aria-hidden="true"></span><svg class="bi bi-book" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M3.214 1.072C4.813.752 6.916.71 8.354 2.146A.5.5 0 018.5 2.5v11a.5.5 0 01-.854.354c-.843-.844-2.115-1.059-3.47-.92-1.344.14-2.66.617-3.452 1.013A.5.5 0 010 13.5v-11a.5.5 0 01.276-.447L.5 2.5l-.224-.447.002-.001.004-.002.013-.006a5.017 5.017 0 01.22-.103 12.958 12.958 0 012.7-.869zM1 2.82v9.908c.846-.343 1.944-.672 3.074-.788 1.143-.118 2.387-.023 3.426.56V2.718c-1.063-.929-2.631-.956-4.09-.664A11.958 11.958 0 001 2.82z" clip-rule="evenodd"/>
                          <path fill-rule="evenodd" d="M12.786 1.072C11.188.752 9.084.71 7.646 2.146A.5.5 0 007.5 2.5v11a.5.5 0 00.854.354c.843-.844 2.115-1.059 3.47-.92 1.344.14 2.66.617 3.452 1.013A.5.5 0 0016 13.5v-11a.5.5 0 00-.276-.447L15.5 2.5l.224-.447-.002-.001-.004-.002-.013-.006-.047-.023a12.582 12.582 0 00-.799-.34 12.96 12.96 0 00-2.073-.609zM15 2.82v9.908c-.846-.343-1.944-.672-3.074-.788-1.143-.118-2.387-.023-3.426.56V2.718c1.063-.929 2.631-.956 4.09-.664A11.956 11.956 0 0115 2.82z" clip-rule="evenodd"/>
                        </svg>&nbsp; Books
                    </a>
                    </li>
                {% endif %}
                {% if user.is_staff %}
                    <li class="{% if request.resolver_match.url_name == 'approval' %}active{%endif%}">
                    <a href="{% url 'book:approval' %}">
                        <span class="glyphicon glyphicon-import" aria-hidden="true"></span>&nbsp;Check requests
                    </a>
                    </li>

                <li class="{% if request.resolver_match.url_name == 'issuedlist' %}active{%endif%}">
                    <a href="{% url 'book:issuedlist' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Issued Book
                    </a>
                    </li>

                {% endif %}

            </ul>

            <ul class="nav navbar-nav navbar-right">


                {% if user.is_authenticated %}
                <li class="{% if request.resolver_match.url_name == 'myissuedbook' %}active{%endif%}">
                    <a href="{% url 'book:myissuedbook' %}">
                        <span class="bi bi-book" aria-hidden="true"></span><svg class="bi bi-book" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M3.214 1.072C4.813.752 6.916.71 8.354 2.146A.5.5 0 018.5 2.5v11a.5.5 0 01-.854.354c-.843-.844-2.115-1.059-3.47-.92-1.344.14-2.66.617-3.452 1.013A.5.5 0 010 13.5v-11a.5.5 0 01.276-.447L.5 2.5l-.224-.447.002-.001.004-.002.013-.006a5.017 5.017 0 01.22-.103 12.958 12.958 0 012.7-.869zM1 2.82v9.908c.846-.343 1.944-.672 3.074-.788 1.143-.118 2.387-.023 3.426.56V2.718c-1.063-.929-2.631-.956-4.09-.664A11.958 11.958 0 001 2.82z" clip-rule="evenodd"/>
                          <path fill-rule="evenodd" d="M12.786 1.072C11.188.752 9.084.71 7.646 2.146A.5.5 0 007.5 2.5v11a.5.5 0 00.854.354c.843-.844 2.115-1.059 3.47-.92 1.344.14 2.66.617 3.452 1.013A.5.5 0 0016 13.5v-11a.5.5 0 00-.276-.447L15.5 2.5l.224-.447-.002-.001-.004-.002-.013-.006-.047-.023a12.582 12.582 0 00-.799-.34 12.96 12.96 0 00-2.073-.609zM15 2.82v9.908c-.846-.343-1.944-.672-3.074-.788-1.143-.118-2.387-.023-3.426.56V2.718c1.063-.929 2.631-.956 4.09-.664A11.956 11.956 0 0115 2.82z" clip-rule="evenodd"/>
                        </svg>&nbsp; My Books
                    </a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'logout' %}active{%endif%}">
                <a href="{% url 'accounts:logout' %}" id="logout">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Log out
                </a>
            </li>
                <li class="active">
                    <a href="{% url 'accounts:profile' user.pk %}"><span aria-hidden="true"></span><b>Librarian: {{user.name}}</b></a>
                </li>
                {% else %}
                <li class="">
                <a href="{% url 'accounts:login' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Log in
                </a>
            </li>
                {% endif %}
            </ul>


        </div>
</div>
</nav>
{% block body %}

{% endblock %}
<script>

</script>
{% block script%}


{% endblock script%}
</body>
</html>

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}
{% block title %}Index{% endblock title %}
{% block body %}
<center>
{% if messages %}
    <ul class="messages" align="center">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
{% endif %}

{% if pending_req %}

    <table class="table table-hover" style='width:60%;margin-top:5%;'>
    <thead><tr><td>User</td><td>Book</td><td>Category</td><td>Issue date</td><td>Return date</td></tr></thead>
    {% for req in pending_req %}
        <form method="post" action="{% url 'book:approval' %}">{% csrf_token %}
            <tr><td><input type="hidden" name="book" value="{{ req.book.id }}"><input type="hidden" name="user_id" value="{{ req.user_id }}">{{ forloop.counter}}. {{ req.user.name }}</td><td>{{ req.book.name }}</td><td>{{ req.book.category.name}}</td><td>{{ req.issued_date }}</td><td>{{ req.return_date }}</td><td><button class="btn btn-default" type="submit">Approve</button><button class="btn btn-danger" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">Reject</button></td></tr>
        </form>

        <div class="modal" id="myModal">
                <div class="modal-dialog">
                  <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                      <h4 class="modal-title">Delete Request</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                            <form method="post" action="{% url 'book:delreq' %}">{% csrf_token %}
                                Are you sure to Reject issue request of <u>{{req.user.name}}</u> for the book <u>{{req.book.name}}?</u><br>
                            <input type="hidden" name="book_id" value="{{ req.book.id }}"><input type="hidden" name="user_id" value="{{ req.user.id }}">
                            <button type="submit" class="btn btn-primary stretched-link" id="btn_book">yes</button>
                            </form>
                    </div>
                    <!-- Modal footer -->
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-dismiss="modal" id="close" onclick="" >close</button>
                    </div>
                </div>
                </div>
              </div>


    {% endfor %}

    </table>

{% endif %}


{% if booklist %}
    <table class="table table-hover" style='width:60%;margin-top:5%;'>
        <thead><tr><td>Book Name</td><td>Category</td><td>Issue date</td><td>Return_date</td><td></td></tr></thead>
    {% for entry in booklist %}
        <form method="post" action="{% url 'book:bookreturn' %}">{% csrf_token %}
            <tr><td><input type="hidden" name="entry_id" value="{{ entry.id }}"><input type="hidden" name="book" value="{{ entry.book.id }}">{{forloop.counter}}. {{ entry.book.name }} by {{entry.book.author}}</td><td>{{ entry.book.category.name }}</td><td>{{ entry.issued_date }}</td><td>{{ entry.return_date }}</td><td><button class="btn btn-default" type="submit">Return</button></td></tr>
        </form>
    {% endfor %}
    {% if book_with_pending %}
        {% for entry in book_with_pending %}
        <form method="post" action="{% url 'book:bookreturn' %}">{% csrf_token %}
            <tr><td><input type="hidden" name="entry_id" value="{{ entry.id }}"><input type="hidden" name="book" value="{{ entry.book.id }}">{{forloop.counter}}. {{ entry.book.name }} by {{entry.book.author}}</td><td>{{ entry.book.category.name }}</td><td>{{ entry.issued_date }}</td><td>{{ entry.return_date }}</td><td><button class="btn btn-default" type="submit">Return</button></td></tr>
        </form>
    {% endfor %}


        {% endif %}
    </table>
{% endif %}


    {% if user.is_authenticated == False %}
    <h1>Welcome to Library management system..</h1>
    <h3>Please login to continue! </h3>
    {% endif %}

</center>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block title %}Login{% endblock title %}
{% block body %}

    <div align="center"><h1>Login</h1>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <table class="table table-hover" style="width:50%;" align="center">
    <form method="POST">
        {% csrf_token %}

        {% for field in form %}
            <tr>
                <td>
                    {{ field.label}}
                </td>
                <td>
                    {{ field }}
                </td>
                <td>
                    {{ field.errors }}
                </td>
            </tr>
        {% endfor%}
        <tr><td></td>
            <td rowspan="3">
                <button class="btn btn-default" type="submit">Login</button>&nbsp;<a class="btn btn-default" href="{% url 'accounts:registration' %}">Sign Up</a>
            </td><td></td>
        </tr>


    </form>
    </table>
    <hr>
</div>

{% endblock body %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block body %}<center>
<h1>Profile</h1>
<hr>
<table class="table table-hover" style="width:40%;">
        <tr>
            <td align="right" style="border:0px;">Name</td>
            <td style="font-weight:bold;border:0px;">: {{ object.name }}</td>
        </tr>

        <tr>
            <td align="right" style="border:0px;">Username</td>
            <td style="font-weight:bold;border:0px;">: {{ object.username }}</td>
        </tr>

        <tr>
            <td align="right" style="border:0px;">Gender</td>
            <td style="font-weight:bold;border:0px;">: {% if object.gender == 'M' %}Male{% else %}Female{% endif %}</td>
        </tr>

        <tr>
            <td align="right" style="border:0px;">Email</td>
            <td style="font-weight:bold;border:0px;">: {{ object.email }}</td>
        </tr>
        <tr>
            <td align="right" style="border:0px;">Contact</td>
            <td style="font-weight:bold;border:0px;">: {{ object.contact }}</td>
        </tr>


</table>
    <a href="{% url 'accounts:update-profile' user.id %}" class="btn btn-default">Update</a>
</div>
{% endblock body %}
</center>

accounts/templates/accounts/registrations.html
{% extends 'accounts/base.html' %}
{% block title %}Registrations{% endblock title %}
{% block body %}



<center><h1>Register Yourself</h1></center>
<!--<p id="error"></p></center>-->
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
<table class="table table-hover" style="width:70%;" align="center">

<form method="POST" id="registration">
    {% csrf_token %}

    {% for field in form %}
        <tr>
            <td>
                {{ field.label}}
            </td>
            <td>
                {{ field }}
            </td>
            <td>
                {{ field.errors }}
            </td>
        </tr>
    {% endfor%}
    <tr><td></td>
        <td rowspan="3">
            <button class="btn btn-default" type="submit" id="id_button" class="btn btn-default">Register</button>
        </td>
    </tr>

</form>
</table>
{% endblock body %}

accounts/templates/accounts/user_form.html
{% extends 'accounts/base.html' %}

{% block body %}<center>
<h1>Profile</h1>
<hr>

<form class="form-horizontal" action="" method="post">
    {% csrf_token %}
    <table class="table table-hover" style="width:40%;">
    {% for field in form %}
    <tr><td>{{ field.label_tag }}</td><td>{{ field }}</td><td>{{ field.errors }}</td></tr>

    {% endfor %}

</table>
<button type="submit" class="btn bnt-success">Submit</button>
</form>

</div>
{% endblock body %}
</center>