book/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [

    url(r'ajax_calls/search/$', views.autocompleteModel),
    path('',views.BookSearch.as_view(),name='booksearch'),
    path('issued/',views.MyIssuedBook.as_view(),name='myissuedbook'),
    path('issued/approval/',views.ApproveReq.as_view(),name='approval'),
    path('issued/return/',views.ReturnBook.as_view(),name='bookreturn'),
    path('issued/delete/',views.DeleteRequest.as_view(),name='delreq'),
    path('list/',views.AllBookList.as_view(),name='booklist'),
    path('list/request/',views.MyRequestList.as_view(),name='reqlist'),
    path('issued/delreq/',views.DeleteRequestUser.as_view(),name='delrequser'),
    path('issued/list/',views.IssuedBooklist.as_view(),name='issuedlist'),
    path('registration/',views.BookCreate.as_view(),name='bookadd'),
    path('update/<int:pk>/',views.BookUpdate.as_view(),name='bookupdate'),
    path('delete/<int:pk>/',views.BookDelete.as_view(),name='bookdelete'),
    path('delete/waitingreq/',views.WaitingReqDelete.as_view(),name='waitingreqdelete'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('book/',include('book.urls')),
]

book/models.py
from django.db import models
from django.urls import reverse

from accounts.models import User


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['name']


class Book(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=50,null=True)
    information = models.CharField(max_length=200)
    total_stock = models.PositiveIntegerField(default=0)
    avail_stock = models.PositiveIntegerField(default=0)

    def __str__(self):
        return '(' + str(self.category) + ') ' + str(self.name)

    def get_absolute_url(self):
        return reverse('book:booklist')

class IssuedBook(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    issued_date = models.DateField()
    return_date = models.DateField()
    status = models.CharField(max_length=10, default='pending')

    def __str__(self):
        return str(self.id)+ ' ' + str(self.user.name) + '-' + str(self.book.name) + '(' + str(self.book.category.name) + ')-' + str(
            self.status)


class WaitingTable(models.Model):
    book = models.OneToOneField(Book, on_delete=models.CASCADE)
    users = models.ManyToManyField(User,through='WaitingQueue')


class WaitingQueue(models.Model):
    users = models.ForeignKey(User, on_delete=models.CASCADE)
    waiting = models.ForeignKey(WaitingTable, on_delete=models.CASCADE)
    request_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.users.name) + ' (' + str(self.waiting.book.name)+ ') '+ str(self.request_time)

book/forms.py
from django import forms

from book.models import Book


class BookRegistrationForm(forms.Form):

    class Meta:
        model = Book
        fields = ('name','author','information')

book/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.db.models import Q
from accounts.forms import RegistrationForm
from accounts.models import User
from .forms import BookRegistrationForm
from .models import Book, IssuedBook, WaitingTable, WaitingQueue
# Create your views here.
from django.views import View, generic
import json
from datetime import datetime, timedelta


def autocompleteModel(request):
    """searchbar autocomplete"""
    if request.is_ajax():
        q = request.GET.get('term')
        search_qs = Book.objects.filter(name__istartswith=q)
        results = []
        for r in search_qs:
            results.append(r.name)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


class BookSearch(View):
    """provides list of all book for search """

    @method_decorator(login_required, name='dispatch')
    def get(self, request):
        return render(request, 'book/book_search.html')

    def post(self, request):
        bookinput = request.POST.get('bookinput').strip()
        searchresult = Book.objects.all().filter(name__iexact=bookinput)
        return render(request, 'book/book_search.html', {'searchresult': searchresult})


class MyIssuedBook(View):
    """ book issue request and user's book list"""

    @method_decorator(login_required, name='dispatch')
    def get(self, request):
        booklist = IssuedBook.objects.filter(user=request.user, status='booked')
        return render(request, 'accounts/index.html', {'booklist': booklist})

    def post(self, request):
        data = request.POST.copy()
        bookinput = Book.objects.get(id=data.get('book'))
        if (IssuedBook.objects.filter(user=request.user, status__in=['booked', 'pending']).count() < 3) and \
                (IssuedBook.objects.filter(
                    Q(user=request.user) & Q(book=bookinput) & Q(status__in=['booked', 'pending'])).count() == 0) and \
                (WaitingQueue.objects.filter(users=request.user,
                                             waiting__book=bookinput).count() == 0):  # User can not issue more than 3 books & user can not issue same book again
            if bookinput.avail_stock > 0:
                # new req to the Issuedbook model if book is available in stock
                new_issue = IssuedBook.objects.create(book=bookinput, user=request.user,
                                                      issued_date=datetime.now().date(),
                                                      return_date=request.POST.get('date'))
                messages.info(request,
                              "Waiting for Librarian's Confirmation..You will be notified by email when its been approved..")
            else:
                waiting_obj, created = WaitingTable.objects.get_or_create(book=bookinput)
                waiting_list = waiting_obj.users.count() + 1
                waiting_obj.users.add(request.user)
                usr_list = ', '.join([usr.name for usr in waiting_obj.users.all()])
                messages.info(request,
                              "Waiting list is " + str(
                                  waiting_obj.users.count()) + ", users --> " + usr_list + ",You will be notified when book is available..")
        else:
            messages.error(request,
                           'You have already issued or request 3 books, return any book in order to issue another..')
            booklist = IssuedBook.objects.filter(user=request.user, status='booked')
            book_with_pending = IssuedBook.objects.filter(user=request.user, status='pending')
            return render(request, 'accounts/index.html',
                          {'booklist': booklist, 'book_with_pending': book_with_pending})
        return render(request, 'accounts/index.html')


class ApproveReq(View):
    """ for Librarian to accept req """

    @method_decorator(login_required, name='dispatch')
    def get(self, request):
        pending_req = IssuedBook.objects.filter(status='pending')
        return render(request, 'accounts/index.html', {'pending_req': pending_req})

    def post(self, request):
        req = IssuedBook.objects.get(book__id=request.POST.get('book'), user__id=request.POST.get('user_id'),
                                     status='pending')
        req.status = 'booked'
        req.save()
        book = Book.objects.get(id=request.POST.get('book'))
        book.avail_stock -= 1
        book.save()
        pending_req = IssuedBook.objects.filter(status='pending')
        messages.info(request, 'Approved book ' + str(req.book.name) + ' for user ' + str(req.user.name))
        return render(request, 'accounts/index.html', {'pending_req': pending_req})


class ReturnBook(View):

    @method_decorator(login_required, name='dispatch')
    def post(self, request):
        obj_del = IssuedBook.objects.filter(id=request.POST.get('entry_id'))
        # obj_del[0].delete()
        obj_del.first().delete()
        book = Book.objects.get(id=request.POST.get('book'))
        book.avail_stock += 1
        book.save()

        # book issue for first user in waiting model
        if book.avail_stock == 1 and WaitingTable.objects.filter(book=book).count() == 1:
            w = WaitingTable.objects.get(book=book)
            first_user = w.waitingqueue_set.all().order_by('request_time').first().users
            new_issue = IssuedBook.objects.create(book=book, user=first_user,
                                                  issued_date=datetime.now().date(),
                                                  return_date=datetime.now().date() + timedelta(days=5))
            w.users.remove(first_user)
            w.save()
            if w.users.count() == 0:  # for last user in waitingtable..
                w.remove()
                w.save()

        messages.info(request, 'Book is returned')
        booklist = IssuedBook.objects.filter(user=request.user, status='booked')
        return render(request, 'accounts/index.html', {'booklist': booklist})


class DeleteRequest(View):
    def post(self, request):
        del_obj = IssuedBook.objects.filter(book__id=int(request.POST.get('book_id')),
                                            user__id=int(request.POST.get('user_id')), status='pending')
        del_obj.delete()
        messages.success(request, 'Request deleted..')
        return redirect('book:approval')


class AllBookList(generic.ListView):
    template_name = 'book/booklist.html'
    paginate_by = 3

    def get_queryset(self):
        return Book.objects.all()


class MyRequestList(View):
    def get(self, request):
        reqlist = IssuedBook.objects.filter(user=request.user, status='pending')
        waiting_list = WaitingQueue.objects.filter(users=request.user)
        print(waiting_list)
        return render(request, 'book/myrequestlist.html', {'object_list': reqlist, 'Waiting_list': waiting_list})


class DeleteRequestUser(View):
    def post(self, request):
        del_obj = IssuedBook.objects.filter(book__id=int(request.POST.get('book_id')),
                                            user__id=int(request.POST.get('user_id')), status='pending')
        del_obj.delete()
        messages.success(request, 'Request deleted..')
        return redirect('book:reqlist')


class IssuedBooklist(View):
    def get(self, request):
        issued_book = IssuedBook.objects.filter(status='booked')
        return render(request, 'book/issuedbooklist.html', {'issued_book': issued_book})


class BookCreate(generic.CreateView):
    model = Book
    fields = '__all__'


class BookUpdate(generic.UpdateView):
    model = Book
    fields = '__all__'


class BookDelete(generic.DeleteView):
    model = Book
    success_url = reverse_lazy('book:booklist')


class WaitingReqDelete(View):
    def post(self, request):
        book = Book.objects.get(id=request.POST.get('book_id'))
        obj_del = WaitingQueue.objects.get(users=request.user).delete()
        w = WaitingTable.objects.get(book=book)
        if w.users.count() == 0:  # for last user in waitingtable..
            w.delete()
        messages.info(request,'Waiting request deleted..')
        return render(request, 'accounts/index.html')

book/templates/book/book_confirm_delete.html
{% extends 'accounts/base.html' %}
{% block body %}
<center>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
</center>
{% endblock %}

book/templates/book/book_form.html
{% extends 'accounts/base.html' %}
{% block body %}
<center><h1>Register Book</h1>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</center>

{% if form %}
<table class="table table-hover" style="width:70%;" align="center">

<form method="POST" id="registration">
    {% csrf_token %}

    {% for field in form %}
        <tr>
            <td>
                {{ field.label}}
            </td>
            <td>
                {{ field }}
            </td>
            <td>
                {{ field.errors }}
            </td>
        </tr>
    {% endfor%}
    <tr><td></td>
        <td rowspan="3">
            <button class="btn btn-default" type="submit" id="id_button" class="btn btn-default">Add</button>
        </td>
    </tr>

</form>
</table>
{% else %}
<h1>No form found</h1>
{% endif %}
{% endblock body %}

book/templates/book/book_search.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block body %}
<center>

<form method="post" action="{% url 'book:booksearch' %}">
    {% csrf_token %}
    <input type="text" id="myInput" name="bookinput">
    <button class="btn btn-default" type="submit" >Check availabilty</button>

</form>


    {% if searchresult %}
    {% for book in searchresult %}

            <table class="table table-hover" style='width:60%;margin-top:5%;'>

            <tr><td><input type="hidden" name="book" value="{{ book.id }}">{{forloop.counter}}. {{ book.name }}</td><td>{% if book.avail_stock > 0 %}In Stock</td>
                <td><button class="btn btn-primary stretched-link" type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Issue now</button>{% else %}Out Stock</td>
                <td><form method="post" action="{% url 'book:myissuedbook' %}">{% csrf_token %}<input type="hidden" name="book" value="{{ book.id }}"><button class="btn btn-primary stretched-link" type="submit" >Advance book</button></form></td></tr>{% endif %}
            </table>

    {% endfor %}
    {% endif %}
            <!-- The Modal -->
              <div class="modal" id="myModal">
                <div class="modal-dialog">
                  <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                      <h4 class="modal-title">For Issueing Book</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        {% for book in searchresult %}
                            <form method="post" action="{% url 'book:myissuedbook' %}">{% csrf_token %}
                            Select Date of Return:<input type="date" name="date" >
                            <input type="hidden" name="book" value="{{ book.id }}">
                            <button type="submit" class="btn btn-primary stretched-link" id="btn_book">Book</button>
                            </form>
                        {% endfor %}
                    </div>
                    <!-- Modal footer -->
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-dismiss="modal" id="close" onclick="" >close</button>
                    </div>
                </div>
                </div>
              </div>
</center>
{% endblock body %}

{% block script %}

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'js/autocomplete.js' %}"></script>

{% endblock script %}

book/templates/book/booklist.html
{% extends 'accounts/base.html' %}

{% block body %}<center>

<a href="{% url 'book:bookadd' %}" class="btn btn-default">Add new book</a>
</center>
    <table class="table table-hover" style="width:100%;">
    <thead>
        <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Author</th>
            <th>Information</th>
        </tr>
    </thead>

        {% for book in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ book.name }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.information }}</td>
                {% if user.is_staff %}<td><a href="{% url 'book:bookupdate' book.id %}" class="glyphicon glyphicon-edit btn btn-danger"></a>
                        <a href="{% url 'book:bookdelete' book.id %}" class="glyphicon glyphicon-remove btn btn-danger"></a></td>{% endif %}
            </tr>
        {% endfor %}
</table>

{% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-default">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-default">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock body %}

book/templates/book/issuedbooklist.html
{% extends 'accounts/base.html' %}
{% block body %}
<center>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

{% if issued_book %}
    <table class="table table-hover" style="width:70%;">
    <thead>
        <tr>
            <th>No.</th>
            <th>Book Name</th>
            <th>Author</th>
            <th>Information</th>
        </tr>
    </thead>
    {% for book in issued_book %}
        <tr><td>{{forloop.counter}}</td><td>{{book.book.name}}</td><td>{{book.book.author}}</td><td>{{book.book.information}}</td></tr>
    {% endfor %}
    </table>
    {% else %}
    <h1> No Request Found..</h1>
{% endif %}
    </center>
{% endblock body %}

book/templates/book/myrequestlist.html
{% extends 'accounts/base.html' %}
{% block body %}
<center>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
{% endif %}

{% if object_list %}
    <h2>Pending Requests</h2>
    <table class="table table-hover" style="width:70%;">
    <thead>
        <tr>
            <th>No.</th>
            <th>Book Name</th>
            <th>Author</th>
            <th>Information</th>
        </tr>
    </thead>
    {% for book in object_list %}
        <tr><td>{{forloop.counter}}</td><td>{{book.book.name}}</td><td>{{book.book.author}}</td><td>{{book.book.information}}</td>
            <td><form method="post" action="{% url 'book:delrequser' %}">{% csrf_token %}<input type="hidden" name="book_id" value="{{ book.book.id }}"><input type="hidden" name="user_id" value="{{ book.user.id }}"><button class="btn btn-default">cancel</button></form></td></tr>
    {% endfor %}
    </table>
{% endif %}


    {% if Waiting_list %}
    <h2>Book in Waiting List</h2>
    <table class="table table-hover" style="width:70%;">
    <thead>
        <tr>
            <th>No.</th>
            <th>Book Name</th>
            <th>Author</th>
            <th>Information</th>
        </tr>
    </thead>

    {% for book in Waiting_list %}
        <tr><td>{{forloop.counter}}</td><td>{{book.waiting.book.name}}</td><td>{{book.waiting.book.author}}</td><td>{{book.waiting.book.information}}</td>
            <td><form method="post" action="{% url 'book:waitingreqdelete'%}">{% csrf_token %}<input type="hidden" name="book_id" value="{{ book.waiting.book.id }}"><input type="hidden" name="user_id" value="{{ book.waiting.user.id }}"><button class="btn btn-default">cancel</button></form></td></tr>
    {% endfor %}
    
    {% endif%}
    </table>

    </center>
{% endblock body %}